import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import Header from '@/components/ui/header1'
import './globals.css'
import {useRouter} from 'next/navigation';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {NextIntlClientProvider} from 'next-intl';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Intimia',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const router = useRouter();
  // console.log("locale "+ router.locale)

  return (
  //   <NextIntlClientProvider
  //   locale={router.locale}
  //   messages={pageProps.messages}
  //   timeZone="Africa/Douala"
  // >
    <html lang="en">
      <body className={`${inter.variable} font-inter antialiased  text-gray-900 tracking-tight`}>
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Header />
          <AppRouterCacheProvider>
           {children}
        </AppRouterCacheProvider>
          {/* {children} */}
          {/* <Banner /> */}
        </div>
      </body>
    </html>
    // </NextIntlClientProvider>

  )
}